name: build_orthanc

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: |
          sudo dpkg --add-architecture i386

          curl -fsSL  https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add -

          sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/

          sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
          sudo apt-get update

          sudo apt-get install -y --install-recommends winehq-stable
          sudo apt-get install -y winetricks
          sudo apt-get install -y winbind
          sudo apt install -y tree g++-mingw-w64

      - name: Build Orthanc
        run: |
          mkdir Build
          cd Build
            cmake ../OrthancServer \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DCMAKE_TOOLCHAIN_FILE=../OrthancServer/Resources/MinGW-W64-Toolchain32.cmake \
                    -DSTANDALONE_BUILD=ON \
                    -DSTATIC_BUILD=ON 
          make

      - name: List files
        run: tree build
