name: build_orthanc

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: sudo apt install -y tree g++-mingw-w64

      - name: Build Orthanc
        run: |
          mkdir Build
          cd Build
            cmake ../OrthancServer \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DCMAKE_TOOLCHAIN_FILE=~/Orthanc/Resources/MinGW-W64-Toolchain32.cmake \
                    -DSTANDALONE_BUILD=ON \
                    -DSTATIC_BUILD=ON \
                    -DUSE_LEGACY_JSONCPP=ON
          make

      - name: List files
        run: tree build
